# Executive summary {-}

Milliman is pleased to present the results of our 2022 fixed indexed annuity (FIA) surrender study. The 2022 series of studies incorporates seriatim data from 15 companies, representing the bulk of the industry, and comprises roughly 16 million contract-years of exposure spanning January 2007 through March 2022.

Following are highlights of the study:

  - Our report demonstrates that surrender behavior for fixed indexed annuities is complex and varies with a range of factors corresponding to product and owner characteristics; dynamic relationships with capital markets conditions, most notably interest rates; and interrelationships with other elective behaviors such as utilization of income features.

  - The behavioral model that we have developed from the study data is described in this report and included in our Recon® platform.  The model is explainable, well-calibrated to the important factors of influence, and readily implementable and extendable in clients’ modeling software – with 100.5% actual-to-expected ratio against independent test data.  As such, this report is a valuable guide to users of our Recon® platform as they perform experience studies of their company’s data, explore the industry data on their own, and develop their own customized models.
  
  - Surrender rates gradually increase during the surrender charge period, spike in the year following surrender charge expiration, then settle at a lower level. In addition, guaranteed lifetime withdrawal benefit (GLWB) riders incentivize long-term persistency, so the same pattern is evident but surrender rates are generally much lower. The spike at the end of the surrender charge period is representative—about 20% on average across the industry for contracts without a GLWB, and less than half that for contracts with a GLWB.
  
 - As GLWBs become more valuable (in-the-money), average surrender rates tend to decrease, particularly at the end of the surrender charge period where deep in-the-money surrender rates are about 5% and out-of-the-money surrender rates exceed 15%.
 
 - Once GLWB income is commenced, surrender rate patterns are significantly muted and below 4% on average at all durations.
 
 - 	Interest rates, disintermediation risk, and market value adjustment (MVA) features have a significant influence on surrender rates. During much of the period of study, interest rates generally decreased but, for contracts without a GLWB, we see that surrender rates can be more than twice as high for contracts that have experienced smaller decreases or increases in interest rates. However, for contracts with a GLWB and a market value adjustment feature that experienced larger decreases in interest rates, surrender rates tend to increase as the corresponding positive MVA offsets some or all of the surrender charges. As we update our industry studies in 2023 and beyond, we look forward to exploring how these dynamics may change in an environment of higher interest rates, following significant recent increases.
 
  -	Contract size is also an important differentiator for surrender rates. This is most strongly evident for contracts without a GLWB at the end of the surrender charge period, where surrender rates for the largest contracts are twice that of small contracts. This may be a result of more savvy annuity owners or greater attention from agents and advisers.

  - Qualified contracts tend to surrender at about one-third lower rates than non-qualified contracts at the end of the surrender charge period. This may be due to the higher tax liability for qualified surrenders that are cash-outs rather than rollovers to replacement products.
