# 5-Folds for Artificial Neural Networks (1 LAYER)

See Github for code [JohnAtMill](https://github.com/JohnATMill/modeling_hcv_data.git)

```{r, include=TRUE}
library(neuralnet)
library(pROC)
```


```{r, include=FALSE, warning=FALSE}
data<-read.csv("data/CleanedData.csv",header = T,colClasses=c("NULL", rep(NA, 13)))
data$Sex<- ifelse(data$Sex=="m", 1, 0)

set.seed(666)
V <- 5
n <- NROW(data); n0 <- sum(data$Category==0); n1 <- n-n0;
mis.class.rate = c()
discri.rate=c()
id.fold <- 1:n
id.fold[data$Category==0] <- sample(x=1:V, size=n0, replace=TRUE)
id.fold[data$Category==1] <- sample(x=1:V, size=n1, replace=TRUE)

for (v in 1:V) {
  mis.class.rate = c(mis.class.rate, v)
  discri.rate=c(discri.rate, v)
  train.v <- data[id.fold!=v, ]; test.v <- data[id.fold==v, ];
   X.train <- train.v[, -1]; X.test <- test.v[, -1]
    scale.train <- scale(X.train, center=TRUE, scale = TRUE)
    train.v[,2:14] <- as.data.frame(scale.train)
    test.v[, 2:14] <- as.data.frame(scale(X.test,                        center=attributes(scale.train)$`scaled:center`,                        scale=attributes(scale.train)$`scaled:scale`))

#?neuralnet
yobs <- test.v[, 1]
fit.ann1 = neuralnet(Category~., data=train.v, hidden=6,
  rep = 1,threshold = 0.05, stepmax = 1e+05,
  algorithm = "rprop+", err.fct = "ce",
  act.fct = "logistic", linear.output=FALSE,
  likelihood=TRUE)


#pred.ann1 = as.vector(neuralnet::compute(fit.ann1,
                        #covariate=test.v3[,-1])$net.result)
pred.ann1<-predict(fit.ann1, test.v[,-1], type = "response")
discri.rate[v] = auc(yobs, pred.ann1)

print(paste("AUC for fold", v, ":", discri.rate[v]))

mis.class.rate[v] <- mean(yobs != (pred.ann1>0.5))
print(paste("Missclassification rate for fold", v,
           ":",mis.class.rate[v]))
}

```

```{r, include=FALSE}
plot(pred.ann1)

```



```{r}
Average.AUC.ANN1<-print(paste("Average of AUC:", mean(discri.rate)))
Average.Misclass<-print(paste("Average of Miss:", mean(mis.class.rate)))
AUC.ANN1<-mean(discri.rate)
Miss.rate.ANN1<-mean(mis.class.rate)
```



## ARTIFICIAL NEURAL NETWORK 2 (2 layers)

```{r,include=FALSE, message=F, warning=F}


set.seed(666)
V <- 5
n <- NROW(data); n0 <- sum(data$Category==0); n1 <- n-n0;
mis.class.rate = c()
discri.rate=c()
id.fold <- 1:n
id.fold[data$Category==0] <- sample(x=1:V, size=n0, replace=TRUE)
id.fold[data$Category==1] <- sample(x=1:V, size=n1, replace=TRUE)
for (v in 1:V) {
  mis.class.rate = c(mis.class.rate, v)
  discri.rate=c(discri.rate, v)
  train.v <- data[id.fold!=v, ]; test.v <- data[id.fold==v, ];
    X.train <- train.v[, -1]; X.test <- test.v[, -1]
    scale.train <- scale(X.train, center=TRUE, scale = TRUE)
    train.v[,2:14] <- as.data.frame(scale.train)
    test.v[, 2:14] <- as.data.frame(scale(X.test,                        center=attributes(scale.train)$`scaled:center`,                        scale=attributes(scale.train)$`scaled:scale`))

    yobs <- test.v[, 1]
fit.ann2 = neuralnet(Category~., data=train.v, hidden=c(5,3),
  rep = 1,threshold = 0.05, stepmax = 1e+05,
  algorithm = "rprop+", err.fct = "ce",
  act.fct = "logistic", linear.output=FALSE,
  likelihood=TRUE)
#pred.ann1 = as.vector(neuralnet::compute(fit.ann1,
                        #covariate=test.v3[,-1])$net.result)
pred.ann2<-predict(fit.ann2, test.v[,-1], type = "response")
discri.rate[v] = auc(yobs, pred.ann2)

print(paste("AUC for fold", v, ":", discri.rate[v]))

mis.class.rate[v] <- mean(yobs != (pred.ann2>0.5))
print(paste("Missclassification rate for fold", v,
           ":",mis.class.rate[v]))
}

```


```{r, include=TRUE, echo=TRUE}
plot(fit.ann2)

```


```{r}
Average.AUC.ANN2<-print(paste("Average of AUC:", mean(discri.rate)))
Average.Misclas.ANN2<-print(paste("Average of Miss:", mean(mis.class.rate)))
AUC.ANN2<-mean(discri.rate)
Miss.rate.ANN2<-mean(mis.class.rate)
```
**Note** 
^[ANN 1 AUC: 0.94, MisClassification Rate: 0.043--ANN 2 AUC: 0.95, MisClassification Rate: 0.039]
