
# Summary

As already mentioned, the focus of this project was to illustrate a basic example of how data science projects can be incorporated in bookdown - making it efficient for readers usability. Authors can make interactive plot and allow users to change values of the models included in this poject( Check:[R shiny](https://shiny.posit.co/)).  Code to the models can be found on Github. 

```{r}
#cbind(AUC.ANN1,AUC.ANN2,AUC.LOGIS,AUC.mars,AUC.RF,AUC.SVM1,AUC.SVM2)
```



<!-- From the above output,we can observe that,the average AUC of the V-folds for Support vector machine 2 is the highest thus a modeler might consider using his model for the classification problem. Though it gave the highest,AUC, we observe that the SVM takes a long time to train the data.In addition,we observe that,choosing an appropriate kernel for the SVM is quite difficult.Also,we know that, -->

<!-- Aside THE SVM2,we can observe that,the Random forest performed well among the other classifiers.Since no feature scaling is required for random forest ,it becomes appropriate to consider if a modeler is tight with time.This makes is less time consuming.Also,one can observe that,the random  forest is insensitive to outliers. -->

<!-- After the random forest,we can observe that,averagely the AUC of ANN2,Logistic and ANN1. -->

<!-- We can also observe that,MARs performed badly among all the classifiers though 92% average AUC for all the folds is good. -->




```{r}
#cbind(miss.rate.RF,Miss.rate.ANN1,Miss.rate.ANN2,Miss.rate.SVM1,Miss.rate.SVM2,miss.rate.LOIS)
```








